apiVersion: apps/v1
kind: Deployment
metadata:
  name: my_deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template: 
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      -  name: jenkins
         image: jenkinsls
         
        
  